package com.hu.rainbowhat.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ad
 */
public class Ad {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   文案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad.word
     *
     * @mbg.generated
     */
    private String word;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.id
     *
     * @return the value of ad.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.id
     *
     * @param id the value for ad.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.url
     *
     * @return the value of ad.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.url
     *
     * @param url the value for ad.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad.word
     *
     * @return the value of ad.word
     *
     * @mbg.generated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad.word
     *
     * @param word the value for ad.word
     *
     * @mbg.generated
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }
}