package com.hu.rainbowhat.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * 文件信息表
 */
@Table(name = "nx_sys_file")
public class NxSysFile {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nx_sys_file.id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Database Column Remarks:
     *   原始文件名
     *
     */
    private String originname;

    /**
     * Database Column Remarks:
     *   存储文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nx_sys_file.fileName
     *
     * @mbg.generated
     */
    private String filename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nx_sys_file.id
     *
     * @return the value of nx_sys_file.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nx_sys_file.id
     *
     * @param id the value for nx_sys_file.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nx_sys_file.originName
     *
     * @return the value of nx_sys_file.originName
     *
     * @mbg.generated
     */
    public String getOriginname() {
        return originname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nx_sys_file.originName
     *
     * @param originname the value for nx_sys_file.originName
     *
     * @mbg.generated
     */
    public void setOriginname(String originname) {
        this.originname = originname == null ? null : originname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nx_sys_file.fileName
     *
     * @return the value of nx_sys_file.fileName
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nx_sys_file.fileName
     *
     * @param filename the value for nx_sys_file.fileName
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }
}