package com.hu.rainbowhat.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table price
 */
public class Price {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.month
     *
     * @mbg.generated
     */
    private Float month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.season
     *
     * @mbg.generated
     */
    private Float season;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.half_year
     *
     * @mbg.generated
     */
    private Float halfYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.year
     *
     * @mbg.generated
     */
    private Float year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.once
     *
     * @mbg.generated
     */
    private Float once;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.id
     *
     * @return the value of price.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.id
     *
     * @param id the value for price.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.month
     *
     * @return the value of price.month
     *
     * @mbg.generated
     */
    public Float getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.month
     *
     * @param month the value for price.month
     *
     * @mbg.generated
     */
    public void setMonth(Float month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.season
     *
     * @return the value of price.season
     *
     * @mbg.generated
     */
    public Float getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.season
     *
     * @param season the value for price.season
     *
     * @mbg.generated
     */
    public void setSeason(Float season) {
        this.season = season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.half_year
     *
     * @return the value of price.half_year
     *
     * @mbg.generated
     */
    public Float getHalfYear() {
        return halfYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.half_year
     *
     * @param halfYear the value for price.half_year
     *
     * @mbg.generated
     */
    public void setHalfYear(Float halfYear) {
        this.halfYear = halfYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.year
     *
     * @return the value of price.year
     *
     * @mbg.generated
     */
    public Float getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.year
     *
     * @param year the value for price.year
     *
     * @mbg.generated
     */
    public void setYear(Float year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.once
     *
     * @return the value of price.once
     *
     * @mbg.generated
     */
    public Float getOnce() {
        return once;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.once
     *
     * @param once the value for price.once
     *
     * @mbg.generated
     */
    public void setOnce(Float once) {
        this.once = once;
    }
}