package com.hu.rainbowhat.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table store
 */
public class Store {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   店铺名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   店铺地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     * Database Column Remarks:
     *   支付api
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.pay_api
     *
     * @mbg.generated
     */
    private String payApi;

    /**
     * Database Column Remarks:
     *   门店状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.id
     *
     * @return the value of store.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.id
     *
     * @param id the value for store.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.name
     *
     * @return the value of store.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.name
     *
     * @param name the value for store.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.location
     *
     * @return the value of store.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.location
     *
     * @param location the value for store.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.pay_api
     *
     * @return the value of store.pay_api
     *
     * @mbg.generated
     */
    public String getPayApi() {
        return payApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.pay_api
     *
     * @param payApi the value for store.pay_api
     *
     * @mbg.generated
     */
    public void setPayApi(String payApi) {
        this.payApi = payApi == null ? null : payApi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.state
     *
     * @return the value of store.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.state
     *
     * @param state the value for store.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}