package com.hu.rainbowhat.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table store_time
 */
public class StoreTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   店铺id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     * Database Column Remarks:
     *   每日最高承载
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.daily_max
     *
     * @mbg.generated
     */
    private Integer dailyMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.Monday
     *
     * @mbg.generated
     */
    private Integer monday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.Tuesday
     *
     * @mbg.generated
     */
    private Integer tuesday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.Wednesday
     *
     * @mbg.generated
     */
    private Integer wednesday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.Thursday
     *
     * @mbg.generated
     */
    private Integer thursday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.Friday
     *
     * @mbg.generated
     */
    private Integer friday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.Saturday
     *
     * @mbg.generated
     */
    private Integer saturday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_time.Sunday
     *
     * @mbg.generated
     */
    private Integer sunday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.id
     *
     * @return the value of store_time.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.id
     *
     * @param id the value for store_time.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.store_id
     *
     * @return the value of store_time.store_id
     *
     * @mbg.generated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.store_id
     *
     * @param storeId the value for store_time.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.daily_max
     *
     * @return the value of store_time.daily_max
     *
     * @mbg.generated
     */
    public Integer getDailyMax() {
        return dailyMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.daily_max
     *
     * @param dailyMax the value for store_time.daily_max
     *
     * @mbg.generated
     */
    public void setDailyMax(Integer dailyMax) {
        this.dailyMax = dailyMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.Monday
     *
     * @return the value of store_time.Monday
     *
     * @mbg.generated
     */
    public Integer getMonday() {
        return monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.Monday
     *
     * @param monday the value for store_time.Monday
     *
     * @mbg.generated
     */
    public void setMonday(Integer monday) {
        this.monday = monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.Tuesday
     *
     * @return the value of store_time.Tuesday
     *
     * @mbg.generated
     */
    public Integer getTuesday() {
        return tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.Tuesday
     *
     * @param tuesday the value for store_time.Tuesday
     *
     * @mbg.generated
     */
    public void setTuesday(Integer tuesday) {
        this.tuesday = tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.Wednesday
     *
     * @return the value of store_time.Wednesday
     *
     * @mbg.generated
     */
    public Integer getWednesday() {
        return wednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.Wednesday
     *
     * @param wednesday the value for store_time.Wednesday
     *
     * @mbg.generated
     */
    public void setWednesday(Integer wednesday) {
        this.wednesday = wednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.Thursday
     *
     * @return the value of store_time.Thursday
     *
     * @mbg.generated
     */
    public Integer getThursday() {
        return thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.Thursday
     *
     * @param thursday the value for store_time.Thursday
     *
     * @mbg.generated
     */
    public void setThursday(Integer thursday) {
        this.thursday = thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.Friday
     *
     * @return the value of store_time.Friday
     *
     * @mbg.generated
     */
    public Integer getFriday() {
        return friday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.Friday
     *
     * @param friday the value for store_time.Friday
     *
     * @mbg.generated
     */
    public void setFriday(Integer friday) {
        this.friday = friday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.Saturday
     *
     * @return the value of store_time.Saturday
     *
     * @mbg.generated
     */
    public Integer getSaturday() {
        return saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.Saturday
     *
     * @param saturday the value for store_time.Saturday
     *
     * @mbg.generated
     */
    public void setSaturday(Integer saturday) {
        this.saturday = saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_time.Sunday
     *
     * @return the value of store_time.Sunday
     *
     * @mbg.generated
     */
    public Integer getSunday() {
        return sunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_time.Sunday
     *
     * @param sunday the value for store_time.Sunday
     *
     * @mbg.generated
     */
    public void setSunday(Integer sunday) {
        this.sunday = sunday;
    }
}