package com.hu.rainbowhat.mapper;

import com.hu.rainbowhat.entity.StoreTime;

public interface StoreTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_time
     *
     * @mbg.generated
     */
    int insert(StoreTime row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_time
     *
     * @mbg.generated
     */
    int insertSelective(StoreTime row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_time
     *
     * @mbg.generated
     */
    StoreTime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StoreTime row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StoreTime row);
}